# Generated by Django 5.2.1 on 2025-05-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.address'),
        ),
    ]
