# Generated by Django 5.2.1 on 2025-05-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_address_transaction_alter_profile_current_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
