# Generated by Django 5.2.1 on 2025-05-30 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
