# Generated by Django 5.2.1 on 2025-06-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.address'),
        ),
    ]
